aws_region       = "us-east-1"
project_name     = "terraform-ec2"
environment      = "prod"
ami_id           = "ami-051e483428ae60e7d"
instance_type    = "t2.micro"
ssh_cidr         = "203.0.113.10/32"
public_key_path  = "~/.ssh/ec2-ssh-public-key.pub"
private_key_path = "~/.ssh/ec2-ssh-private-key"
